package com.camellia.ordersystem.repo;

import com.camellia.ordersystem.entity.MenuItemEntity;
import com.camellia.ordersystem.entity.MenuItemNoteEntity;
import com.camellia.ordersystem.entity.MenuItemOptionEntity;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.*;

/**
 * Integration tests for MenuItemRepository LazyInitializationException regression prevention.
 * Generated by Test Generator / Regression Guard agent.
 * 
 * These tests verify that the @EntityGraph annotation on findAll() correctly eager-loads
 * the 'options' and 'notes' collections, preventing LazyInitializationException when
 * accessing these collections outside the transaction boundary.
 * 
 * WITHOUT @EntityGraph: These tests would FAIL with LazyInitializationException
 * WITH @EntityGraph: These tests PASS with collections fully initialized
 */
@DataJpaTest
public class MenuItemRepositoryTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private MenuItemRepository repository;

    /**
     * Core regression test: Verifies that findAll() with @EntityGraph eagerly loads
     * options and notes collections, allowing access outside transaction boundary.
     * 
     * This test reproduces the exact failure scenario from the bug.
     */
    @Test
    public void testFindAll_LoadsOptionsAndNotesEagerly_NoLazyInitializationException() {
        // ARRANGE: Create test data with options and notes
        MenuItemEntity menuItem = new MenuItemEntity();
        menuItem.setItemName("Espresso");
        menuItem.setItemPrice(new BigDecimal("3.50"));
        menuItem.setSoldout(false);
        entityManager.persist(menuItem);

        MenuItemOptionEntity option1 = new MenuItemOptionEntity();
        option1.setMenuItem(menuItem);
        option1.setOptionName("Extra Shot");
        option1.setOptionPrice(new BigDecimal("0.50"));
        entityManager.persist(option1);

        MenuItemOptionEntity option2 = new MenuItemOptionEntity();
        option2.setMenuItem(menuItem);
        option2.setOptionName("Oat Milk");
        option2.setOptionPrice(new BigDecimal("0.75"));
        entityManager.persist(option2);

        MenuItemNoteEntity note1 = new MenuItemNoteEntity();
        note1.setMenuItem(menuItem);
        note1.setNoteName("No Sugar");
        note1.setNotePrice(BigDecimal.ZERO);
        entityManager.persist(note1);

        entityManager.flush();
        
        // ACT: Clear persistence context to simulate transaction boundary
        entityManager.clear();
        List<MenuItemEntity> items = repository.findAll();

        // ASSERT: Access collections OUTSIDE transaction
        // WITHOUT @EntityGraph: LazyInitializationException
        // WITH @EntityGraph: Works correctly
        assertThat(items).hasSize(1);
        MenuItemEntity retrievedItem = items.get(0);
        
        assertThatNoException().isThrownBy(() -> {
            List<MenuItemOptionEntity> options = retrievedItem.getOptions();
            assertThat(options).hasSize(2);
            assertThat(options)
                .extracting(MenuItemOptionEntity::getOptionName)
                .containsExactlyInAnyOrder("Extra Shot", "Oat Milk");
            assertThat(options)
                .extracting(MenuItemOptionEntity::getOptionPrice)
                .containsExactlyInAnyOrder(new BigDecimal("0.50"), new BigDecimal("0.75"));
        });
        
        assertThatNoException().isThrownBy(() -> {
            List<MenuItemNoteEntity> notes = retrievedItem.getNotes();
            assertThat(notes).hasSize(1);
            assertThat(notes)
                .extracting(MenuItemNoteEntity::getNoteName)
                .containsExactly("No Sugar");
            assertThat(notes)
                .extracting(MenuItemNoteEntity::getNotePrice)
                .containsExactly(BigDecimal.ZERO);
        });
    }

    @Test
    public void testFindAll_WithEmptyCollections_NoException() {
        // ARRANGE: Menu item with no options or notes
        MenuItemEntity menuItem = new MenuItemEntity();
        menuItem.setItemName("Black Coffee");
        menuItem.setItemPrice(new BigDecimal("2.00"));
        menuItem.setSoldout(false);
        entityManager.persist(menuItem);
        entityManager.flush();
        entityManager.clear();

        // ACT
        List<MenuItemEntity> items = repository.findAll();

        // ASSERT: Empty collections should be accessible
        assertThat(items).hasSize(1);
        MenuItemEntity retrievedItem = items.get(0);
        
        assertThatNoException().isThrownBy(() -> {
            assertThat(retrievedItem.getOptions()).isEmpty();
            assertThat(retrievedItem.getNotes()).isEmpty();
        });
    }

    @Test
    public void testFindAll_MultipleMenuItems_AllCollectionsLoaded() {
        // ARRANGE: Multiple menu items with varying collections
        MenuItemEntity item1 = new MenuItemEntity();
        item1.setItemName("Latte");
        item1.setItemPrice(new BigDecimal("4.50"));
        item1.setSoldout(false);
        entityManager.persist(item1);

        MenuItemOptionEntity option1 = new MenuItemOptionEntity();
        option1.setMenuItem(item1);
        option1.setOptionName("Vanilla Syrup");
        option1.setOptionPrice(new BigDecimal("0.50"));
        entityManager.persist(option1);

        MenuItemEntity item2 = new MenuItemEntity();
        item2.setItemName("Cappuccino");
        item2.setItemPrice(new BigDecimal("4.00"));
        item2.setSoldout(true);
        entityManager.persist(item2);

        MenuItemNoteEntity note1 = new MenuItemNoteEntity();
        note1.setMenuItem(item2);
        note1.setNoteName("Extra Foam");
        note1.setNotePrice(BigDecimal.ZERO);
        entityManager.persist(note1);

        MenuItemNoteEntity note2 = new MenuItemNoteEntity();
        note2.setMenuItem(item2);
        note2.setNoteName("Light Roast");
        note2.setNotePrice(BigDecimal.ZERO);
        entityManager.persist(note2);

        MenuItemEntity item3 = new MenuItemEntity();
        item3.setItemName("Americano");
        item3.setItemPrice(new BigDecimal("3.00"));
        item3.setSoldout(false);
        entityManager.persist(item3);

        entityManager.flush();
        entityManager.clear();

        // ACT
        List<MenuItemEntity> items = repository.findAll();

        // ASSERT: All collections accessible
        assertThat(items).hasSize(3);

        assertThatNoException().isThrownBy(() -> {
            MenuItemEntity latte = items.stream()
                .filter(i -> "Latte".equals(i.getItemName()))
                .findFirst().orElseThrow();
            assertThat(latte.getOptions()).hasSize(1);
            assertThat(latte.getNotes()).isEmpty();

            MenuItemEntity cappuccino = items.stream()
                .filter(i -> "Cappuccino".equals(i.getItemName()))
                .findFirst().orElseThrow();
            assertThat(cappuccino.getOptions()).isEmpty();
            assertThat(cappuccino.getNotes()).hasSize(2);

            MenuItemEntity americano = items.stream()
                .filter(i -> "Americano".equals(i.getItemName()))
                .findFirst().orElseThrow();
            assertThat(americano.getOptions()).isEmpty();
            assertThat(americano.getNotes()).isEmpty();
        });
    }

    @Test
    public void testFindAll_StreamAndMapPattern_NoException() {
        // ARRANGE: Menu item with collections
        MenuItemEntity menuItem = new MenuItemEntity();
        menuItem.setItemName("Mocha");
        menuItem.setItemPrice(new BigDecimal("5.00"));
        menuItem.setSoldout(false);
        entityManager.persist(menuItem);

        MenuItemOptionEntity option1 = new MenuItemOptionEntity();
        option1.setMenuItem(menuItem);
        option1.setOptionName("Whipped Cream");
        option1.setOptionPrice(new BigDecimal("0.50"));
        entityManager.persist(option1);

        MenuItemOptionEntity option2 = new MenuItemOptionEntity();
        option2.setMenuItem(menuItem);
        option2.setOptionName("Chocolate Drizzle");
        option2.setOptionPrice(new BigDecimal("0.75"));
        entityManager.persist(option2);

        MenuItemNoteEntity note1 = new MenuItemNoteEntity();
        note1.setMenuItem(menuItem);
        note1.setNoteName("Decaf");
        note1.setNotePrice(BigDecimal.ZERO);
        entityManager.persist(note1);

        entityManager.flush();
        entityManager.clear();

        // ACT
        List<MenuItemEntity> items = repository.findAll();

        // ASSERT: Simulate exact controller pattern
        assertThatNoException().isThrownBy(() -> {
            items.stream().forEach(item -> {
                List<String> optionNames = item.getOptions().stream()
                    .map(MenuItemOptionEntity::getOptionName)
                    .collect(Collectors.toList());
                
                List<String> noteNames = item.getNotes().stream()
                    .map(MenuItemNoteEntity::getNoteName)
                    .collect(Collectors.toList());
                
                assertThat(optionNames).containsExactlyInAnyOrder("Whipped Cream", "Chocolate Drizzle");
                assertThat(noteNames).containsExactly("Decaf");
            });
        });
    }
}
